version: "3.1"
services:
  nginx4:
    image: nginx:latest
    container_name: nginx4
    ports:
      - "80:80"
      - "443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app4
    #env_file: ./.env

  app4:
    image: node:14-alpine
    container_name: app4
    working_dir: /app
    volumes:
      - .:/app
    restart: always
    links:
      - mysql4
      - redis4
    ports:
      - "5000:5000"
    #entrypoint: /bin/bash
    command: node api/app.js
    #command: bash ping google.com.ar
    #env_file: ./.env
    environment:
      "NODE_ENV": "docker-compose"

  mysql4:
    #env_file: ./.env.docker-compose
    image: mysql:5.7
    container_name: mysql4
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_ROOT_PASSWORD}"

  redis4:
    image: redis:alpine
    container_name: redis4
    ports:
      - "6379:6379"

